apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox1
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: tmpdir
  - args:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox2
    resources: {}
    volumeMounts:
    - mountPath: /etc/foo
      name: tmpdir
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: tmpdir
    emptyDir: {}
status: {}
